### ISSUE TITLE
DrawPCABasisSample: shouldn't the meanvector be added to get a valid sample?

### ISSUE THREAD

**Issue by zarquon42b** [statismo/statismo#246]
Sorry for being such a pain in the a** but as I am implementing more member functions, I stumbled across another (possible) issue:
Shouldn't [this](https://github.com/statismo/statismo/blob/develop/modules/core/include/StatisticalModel.hxx#L163) be 
```
return m_representer->SampleVectorToSample(m_pcaBasisMatrix.col(pcaComponent)+this->GetMeanVector());
``` 

instead of 
```
return m_representer->SampleVectorToSample(m_pcaBasisMatrix.col(pcaComponent));
``` 
(adding the mean back) to get a valid sample? Otherwise you simply get the basis vector transformed into a sample (e.g. a vtkPolydata with the vertices consisting of the basis vector entries.)

**Comment by marcelluethi** [comment]
Not at all! Your comments are helpful and highly appreciated.

The original idea of this method was to get a sample that corresponds to the component. This can sometimes be useful, especially when you work with deformation fields. We use it for example in the registration code, in order to get
interpolated versions of the basis:
https://github.com/statismo/statismo/blob/develop/modules/ITK/include/itkInterpolatingStatisticalDeformationModelTransform.h#L114
This makes it possible to use a deformation model that is defined on a coarse image grid, while still having decent accuracy in the registration.

When you use meshes, this method does not make much sense (and this is  clearly a design flaw in statismo).
You can, however, get the components you want by calling DrawSample(coeffs), with the i-th entry set to 1 and all others zero (if you want to get the component corresponding to the i-th PCA component).

**Comment by zarquon42b** [comment]
Ah, thanks, yes, in this scenario this makes perfect sense. After implementing this function, I was wondering what I am supposed to do with it (especially, as you pointed out, this is just a version of DrawSample() for unit vectors).
